# Generated by Django 4.2 on 2023-04-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='My_portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_description', models.TextField()),
                ('sm_link', models.URLField(blank=True, db_index=True, max_length=128, unique=True)),
            ],
        ),
    ]
