# Generated by Django 4.2 on 2023-04-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sageer_kv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='my_portfolio',
            old_name='sm_link',
            new_name='sm_link1',
        ),
        migrations.AddField(
            model_name='my_portfolio',
            name='sm_link2',
            field=models.URLField(blank=True, db_index=True, max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='my_portfolio',
            name='sm_link3',
            field=models.URLField(blank=True, db_index=True, max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='my_portfolio',
            name='sm_link4',
            field=models.URLField(blank=True, db_index=True, max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='my_portfolio',
            name='sm_link5',
            field=models.URLField(blank=True, db_index=True, max_length=128, unique=True),
        ),
    ]
