# Generated by Django 4.2 on 2023-04-28 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sageer_kv', '0002_rename_sm_link_my_portfolio_sm_link1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='my_portfolio',
            old_name='sm_link1',
            new_name='fb_link',
        ),
        migrations.RenameField(
            model_name='my_portfolio',
            old_name='sm_link2',
            new_name='insta_link',
        ),
        migrations.RenameField(
            model_name='my_portfolio',
            old_name='sm_link3',
            new_name='lnkdn_link',
        ),
        migrations.RenameField(
            model_name='my_portfolio',
            old_name='sm_link4',
            new_name='sm_gtb_link',
        ),
        migrations.RenameField(
            model_name='my_portfolio',
            old_name='sm_link5',
            new_name='twtr_link',
        ),
    ]
