# Generated by Django 4.2 on 2023-04-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sageer_kv', '0006_delete_mymodel_my_portfolio_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_portfolio',
            name='home_img',
            field=models.ImageField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
