# Generated by Django 4.2 on 2023-04-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sageer_kv', '0007_my_portfolio_home_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_portfolio',
            name='about_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='my_portfolio',
            name='about_head',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='my_portfolio',
            name='about_img',
            field=models.ImageField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='my_portfolio',
            name='about_link',
            field=models.URLField(blank=True, db_index=True, max_length=128, unique=True),
        ),
    ]
