# Generated by Django 4.2 on 2023-04-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sageer_kv', '0008_my_portfolio_about_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_portfolio',
            name='icon_link',
            field=models.URLField(blank=True, db_index=True, max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='my_portfolio',
            name='services_description',
            field=models.TextField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='my_portfolio',
            name='services_head',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='my_portfolio',
            name='services_link',
            field=models.URLField(blank=True, db_index=True, max_length=128, unique=True),
        ),
    ]
