# Generated by Django 4.2 on 2023-04-30 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sageer_kv', '0010_rename_services_description_my_portfolio_portfolio_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='my_portfolio',
            old_name='portfolio_description',
            new_name='porject_description',
        ),
        migrations.RenameField(
            model_name='my_portfolio',
            old_name='portfolio_head',
            new_name='porject_head',
        ),
        migrations.RenameField(
            model_name='my_portfolio',
            old_name='portfolio_img',
            new_name='porject_img',
        ),
        migrations.RenameField(
            model_name='my_portfolio',
            old_name='portfolio_link',
            new_name='porject_link',
        ),
    ]
