# Generated by Django 4.2 on 2023-04-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sageer_kv', '0012_portfolio_remove_my_portfolio_porject_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='portfolio',
        ),
        migrations.AddField(
            model_name='my_portfolio',
            name='porject_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='my_portfolio',
            name='porject_head',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='my_portfolio',
            name='porject_img',
            field=models.ImageField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='my_portfolio',
            name='porject_link',
            field=models.URLField(blank=True, db_index=True, max_length=128, unique=True),
        ),
    ]
