# Generated by Django 4.2 on 2023-05-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sageer_kv', '0013_delete_portfolio_my_portfolio_porject_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porject_img', models.ImageField(upload_to='uploads/')),
                ('porject_head', models.TextField()),
                ('porject_description', models.TextField()),
                ('porject_link', models.URLField(blank=True, db_index=True, max_length=128, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='my_portfolio',
            name='porject_description',
        ),
        migrations.RemoveField(
            model_name='my_portfolio',
            name='porject_head',
        ),
        migrations.RemoveField(
            model_name='my_portfolio',
            name='porject_img',
        ),
        migrations.RemoveField(
            model_name='my_portfolio',
            name='porject_link',
        ),
    ]
