# Generated by Django 4.2 on 2023-07-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sageer_kv', '0017_alter_experience_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
