# Generated by Django 4.2 on 2023-07-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sageer_kv', '0018_date_is_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company_website',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
