# Generated by Django 4.2 on 2023-07-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sageer_kv', '0021_alter_service_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_icon',
            field=models.CharField(choices=[('bx bx-code-alt', 'Web Development'), ('bx bxs-paint', 'Graphic Design'), ('bx bx-code-block', 'Power apps')], max_length=50),
        ),
    ]
