# Generated by Django 4.2 on 2023-07-24 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sageer_kv', '0025_footerinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerinfo',
            name='fb_link',
        ),
        migrations.RemoveField(
            model_name='footerinfo',
            name='gtb_link',
        ),
        migrations.RemoveField(
            model_name='footerinfo',
            name='insta_link',
        ),
        migrations.RemoveField(
            model_name='footerinfo',
            name='lnkdn_link',
        ),
        migrations.RemoveField(
            model_name='footerinfo',
            name='twtr_link',
        ),
    ]
